name: attendance_app
description: Aplicación multiplataforma de gestión de asistencia con reconocimiento facial.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Arquitectura y estado
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  dartz: ^0.10.1

  # Base de datos y almacenamiento
  supabase_flutter: ^1.10.14
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.0
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0

  # Autenticación
  google_sign_in: ^6.1.4
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0

  # Cámara y gestión de imágenes
  camera: ^0.10.5+2
  image: ^4.0.17
  path: ^1.8.3
  image_picker: ^1.0.1

  # Geolocalización
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  google_maps_flutter: ^2.3.3
  google_maps_flutter_web: ^0.5.3

  # Reconocimiento facial
  google_ml_kit: ^0.16.2
  tflite_flutter: ^0.10.1

  # UI
  flutter_signature_pad: ^3.0.1
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.5
  flutter_platform_widgets: ^3.3.5
  intl: ^0.18.1
  shimmer: ^3.0.0
  lottie: ^2.5.0

  # Generación de reportes
  pdf: ^3.10.4
  printing: ^5.11.0
  excel: ^2.1.0
  file_picker: ^5.3.2
  file_saver: ^0.2.4
  syncfusion_flutter_pdf: ^22.1.39
  syncfusion_flutter_xlsio: ^22.1.39
  open_file: ^3.3.2
  universal_html: ^2.2.3

  # Conectividad y sincronización
  connectivity_plus: ^4.0.1
  workmanager: ^0.5.1
  background_fetch: ^1.2.0

  # Utilidades
  logger: ^1.4.0
  rxdart: ^0.27.7
  uuid: ^3.0.7
  permission_handler: ^10.4.3
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  flutter_lints: ^2.0.2
  build_runner: ^2.4.13
  bloc_test: ^9.1.3
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/ml_models/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300